### ISSUE TITLE
Failed to compile with Scala 2.13 and spark 3.5.1

### ISSUE THREAD

**Issue by woestler** [vesoft-inc/nebula-spark-connector#150]
**General Question**

Failed to compile with Scala 2.13 and spark 3.5.1

我将pom中的scala版本改为2.13， spark的版本改为3.5.1，以满足我们项目的要求，但是在编译nebula-spark-connector时出错了， 错误如下：

```
[ERROR] /home/workspace/nebula-spark-connector/nebula-spark-connector_3.0/src/main/scala/com/vesoft/nebula/connector/NebulaDataSource.scala:40: error: Symbol 'type scala.package.Serializable' is missing from the classpath.
[INFO] This symbol is required by 'class com.vesoft.nebula.connector.NebulaOptions'.
[INFO] Make sure that type Serializable is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[INFO] A full rebuild may help if 'NebulaOptions.class' was compiled against an incompatible version of scala.package.
[INFO]   private var nebulaOptions: NebulaOptions = _
[INFO]                              ^
[ERROR] error: scala.reflect.internal.MissingRequirementError: object scala.$less$colon$less in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:24)
```
